services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ~/docker_vol/mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    volumes:
      - ~/docker_vol/chromadb_data:/chroma
    environment:
      IS_PERSISTENT: "true"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-cv-evaluator-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - chromadb
    env_file:
      - ./.env
